all:
  hosts:
    worker1:
      ansible_host: d7525-10s10327.wisc.cloudlab.us
      ansible_user: sa_lamer
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      cluster_ip: 192.168.55.2
    worker2:
      ansible_host: d7525-10s10331.wisc.cloudlab.us
      ansible_user: sa_lamer
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      cluster_ip: 192.168.55.3
  children:
    workers:
      hosts:
        worker1:
        worker2:
