all:
  hosts:
    worker1:
      ansible_host: amd234.utah.cloudlab.us
      ansible_user: sa_lamer
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      cluster_ip: 192.168.55.2
    worker2:
      ansible_host: amd214.utah.cloudlab.us
      ansible_user: sa_lamer
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      cluster_ip: 192.168.55.3
    worker3:
      ansible_host: amd217.utah.cloudlab.us
      ansible_user: sa_lamer
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      cluster_ip: 192.168.55.4
    #worker4:
    #  ansible_host: amd227.utah.cloudlab.us
    #  ansible_user: sa_lamer
    #  ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    #  cluster_ip: 192.168.55.5
  children:
    workers:
      hosts:
        worker1:
        worker2:
        worker3:
       # worker4:
