all:
  hosts:
    master:
      ansible_host: hp069.utah.cloudlab.us
      ansible_user: sa_lamer
      ansible_ssh_priva_key_filete: ~/.ssh/id_ed25519
      cluster_ip: 192.168.55.1
  children:
    masters:
      hosts:
        master:
