all:
  hosts:
    master:
      ansible_host: c240g5-110229.wisc.cloudlab.us
      ansible_user: sa_lamer
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      cluster_ip: 192.168.55.1
  children:
    masters:
      hosts:
        master:
