- name: OVS setup
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install OpenVswitch
      apt:
        name:
          - openvswitch-switch
        state: present
